[project]
name = "etiennecollin"
version = "0.1.0"
description = "This is a system environment."
requires-python = ">=3.12"
dependencies = [
    "ansible>=8.7.0",
    "gpg>=1.10.0",
    "neovim>=0.3.1",
    "unidecode>=1.3.8",
]
