git:
  paging:
    colorArg: always
    pager: delta --no-gitconfig --diff-so-fancy --line-numbers --wrap-right-percent 1 --dark --paging=never
os:
  editPreset: "nvim"
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim +{{line}} {{filename}}"
  editInTerminal: true
  openDirInEditor: "nvim {{dir}}"
