git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --no-gitconfig --diff-so-fancy --line-numbers --wrap-right-percent 1 --dark --paging=never
os:
  editPreset: "nvim-remote"

customCommands:
  - key: "<c-p>"
    description: "Push to a specific branch"
    context: "localBranches"
    loadingText: "Pushing..."
    prompts:
      - type: "input"
        title: "Push to remote:"
        key: "Remote"
        initialValue: "{{.SelectedRemote.Name}}"
        suggestions:
          preset: "remotes"
      - type: "input"
        title: "Push to branch:"
        key: "Branch"
        suggestions:
          preset: "branches"
      - type: "menu"
        title: "Command:"
        key: "Cmd"
        options:
          - value: "push"
          - value: "push --force-with-lease"
          - value: "push --force"
    command: "git {{.Form.Cmd}} {{.Form.Remote}} HEAD:{{.Form.Branch | quote}}"

  - key: "<c-p>"
    description: "Push selected commit to a specific branch"
    context: "commits"
    loadingText: "Pushing commit..."
    prompts:
      - type: "input"
        title: "Push to remote:"
        key: "Remote"
        initialValue: "{{.SelectedRemote.Name}}"
        suggestions:
          preset: "remotes"
      - type: "input"
        title: "Push to branch:"
        key: "Branch"
        suggestions:
          preset: "branches"
      - type: "menu"
        title: "Command:"
        key: "Cmd"
        options:
          - value: "push"
          - value: "push --force-with-lease"
          - value: "push --force"
    command: "git {{.Form.Cmd}} {{.Form.Remote}} {{.SelectedCommit.Sha}}:{{.Form.Branch | quote}}"

  - key: "P"
    description: "Push selected commit (and any preceding) to current branch's upstream"
    context: "commits"
    loadingText: "Pushing..."
    prompts:
      - type: "input"
        title: "Push to remote:"
        key: "Remote"
        initialValue: "{{.SelectedRemote.Name}}"
        suggestions:
          preset: "remotes"
      - type: "menu"
        title: "Command:"
        key: "Cmd"
        options:
          - value: "push"
          - value: "push --force-with-lease"
          - value: "push --force"
    command: "git {{.Form.Cmd}} {{.Form.Remote}} {{.SelectedCommit.Sha}}:{{.SelectedLocalBranch.Name}}"
