alias ls="ls --color=auto"
alias la="ls -a --color=auto"
alias less="less -R"
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias a="zellij attach --create main"
alias z="zellij options --serialize-pane-viewport false --session-serialization false"
alias imgcat="wezterm imgcat"
alias rm="trash"
alias sshp="ssh -L 8080:localhost:8080 -L 11434:localhost:11434 -L 8888:localhost:8888"
alias lg="lazygit"
alias cm="chezmoi"

alias jekyll="bundle exec jekyll serve --livereload"
alias leptosfmt="leptosfmt -m 120 src/**/*.rs"
alias tserve="trunk serve --open"
alias typstw="typst watch --root ~ --open sioyek"
alias typstc="typst compile --root ~"
alias pytypstw="python -m typst_pyimage -w -a \"--root ~ --open sioyek\""

alias format="python /Users/etiennecollin/github/gist/file_system_formatter.py"
alias office2pdf="/Users/etiennecollin/github/gist/office_to_pdf.sh"
alias uni="cd ~/Desktop/university/semester-4/"
